# Toggle in game: Right Shift + F12
legacy_layout=false
position=top-left
round_corners=10
background_alpha=0.75
background_color=1d2021
font_size=20
text_color=ebdbb2
table_columns=3

gpu_stats
gpu_temp
gpu_power
gpu_color=fe8019
gpu_text=7800 XT
cpu_stats
cpu_temp
cpu_color=8ec07c
cpu_text=12700KF
vram
vram_color=d3869b
ram
ram_color=83a598
fps
fps_color_change
fps_color=fb4934,fabd2f,b8bb26
fps_value=60,144
frametime
frame_timing
frametime_color=fabd2f
gamemode
engine_color=fe8019
toggle_hud=Shift_R+F12
